### ISSUE TITLE
Consider making `Send` a monad transformer

### ISSUE THREAD

**Issue by ambroslins** [anton-k/mig#49]
I think `Send` should be a proper monad transformer (isomorphic to `IdentityT`).

This allows users who use the standard monads (e.g. `MonadReader`, `MonadError` etc.),
to omit the `Send` constructor just write the route handler in the `Send` monad.

Users with a custom monad class can trivially implement a instance of their class for the `Send` monad and also write everything in it.

Users who are some not able to trivially implement a instance for `Send` (e.g. effect systems) will just have to call `lift` or use the `Send` constructor.

I think most users fall into the first two categories and there benefit from this change and there is no downside for the third group.

If you think this might be worth a try I can implement a prototype.

**Comment by anton-k** [comment]
That can be done, although I was happy to not to introduce any custom monads,
as it's compatible with current version it's ok to add it.

Although you trade here one `Send` word for several liftIO's.

**Comment by anton-k** [comment]
Also it's iteresting to consider to built Response into that monad so that `ok` can become part of the pure.
It would be great if `bad` would become `throwError` although it also requires a status with response message.
So probably it could lead to introduction of some error type and it can quickly become messy.

**Comment by ambroslins** [comment]
> Although you trade here one `Send` word for several liftIO's.

If the entire handler is written in plain `IO` we can just call `liftIO` once before the `do` block, just like with `Send`. 

> Also it's interesting to consider to built Response into that monad so that ok can become part of the pure. It would be great if bad would become throwError although it also requires a status with response message.S o probably it could lead to introduction of some error type and it can quickly become messy.

Yes I have also thought about this. To define the monad and runner like this:
```haskell
newtype Send method m a = Send (ExceptT Response m a)

runSend :: ToRespBody a => Send method m a => m Response
```
However this would also make it weird to add headers to the returned result. So I am not to sure about this either.
