### ISSUE TITLE
Simplify `Response`, `Resp` and `IsResp`

### ISSUE THREAD

**Issue by ambroslins** [anton-k/mig#50]
I think all of the Responses can be simplified to a single data type like this:
```haskell
data Response a = Response
  { status :: Status
  , headers :: ResponseHeaders
  , body :: ResponseBody
  }
```
with the following functions:
```haskell
ok :: ToRespBody a => a -> Response a
bad :: ToRespBody a => Status -> a -> Response b
```

I would also drop the phantom type for the `MediaType` and instead use newtype wrappers like:
```haskell
newtype Json a = Json a

instance ToMediaType (Json a) where ...
instance ToJson a => ToRespBody (Json a) where ...
```

In my opinion phantom types are a litte more advanced concept and does not provide enough benefit (maybe I am just missing the real benefit here, please let me know) to justify the lost simplicity. Newtype wrappers to provides instances are a well know concept in the Haskell ecosystem.

Again, if this might be a interesting for you I can implement a prototype to further discuss the details.

**Comment by ambroslins** [comment]
This and the other two issues (#49 and #51) primarily focus on "simplicity" which of course is highly subjective.
I have been looking for a library like this (between servant and the other web frameworks) for a long time. And also unsuccessfully tried myself. And when I saw the post on reddit I got very excited about this. However for my taste the recent changes moved it a little closer to servant than I would like. So I would like to try to pull it back a little bit into the other direction. However I would also like to not sabotage this project, so if you want to chose a different direction please let me know when I should stop.

**Comment by anton-k** [comment]
This does not work because we need two types `Resp` and `RespOr` if type of the error is different from the type of the result.
That's why class `IsResp` was introduced. To unify both of those cases.

**Comment by anton-k** [comment]
Also I would like to have the result type in the argument of the `Resp`. So I'm against unifying both cases to `ByteString`.

**Comment by ambroslins** [comment]
But we can construct a `Response a` from any other type `b`, see the signature of the `bad` function in the example.

**Comment by ambroslins** [comment]
```haskell
squareRoot :: Query "arg" Float -> Get (Response (Json Float))
squareRoot (Query arg) = Send $ pure $ 
  if (arg >= 0) 
    then ok $ Json (sqrt arg) 
    else bad @Text status500 "Negative input"
```
We need the explicit type application because the type would be ambiguous. Assuming we are using `OverloadedStrings`, if not the type would be inferred as string.

Maybe we could move the `Response` inside `Get` and even define `ok` as:
```haskell
ok :: (Coercieble a b, ToRespBody b) => a -> Response b
```
This would allow us write it like this:
```haskell
squareRoot :: Query "arg" Float -> Get (Json Float)
squareRoot (Query arg) = Send $ pure $ 
  if (arg >= 0) 
    then ok (sqrt arg) 
    else bad @Text status500 "Negative input"
```
However we would have to check whether the `Coercible` will lead to ambiguous types in some cases.

**Comment by anton-k** [comment]
```haskell
else bad @Text status500 "Negative input"
```

this case deceives the user. We state that result type is `float`  but by some magic we use `Text`.
I like to have explicit statement in the type signature.
