### ISSUE TITLE
Dependency footprint

### ISSUE THREAD

**Issue by ambroslins** [anton-k/mig#51]
The [openapi3](https://hackage.haskell.org/package/openapi3) and [insert-ordered-containers](https://hackage.haskell.org/package/insert-ordered-containers) both have a pretty big dependency footprint (e.g. both depend on [lens](https://hackage.haskell.org/package/lens)). This might be a bit much for just the core library. I could not find a usage of the `insert-ordered-containers` (did I miss something?) so that should be easy.

Maybe we can replace `openapi3` with a small custom type (like `RouteInfo`) to keep track of the route spec and then provide a separate package to convert this type to the full `OpenApi` schema. However this probably means we lose the ability to use the `ToSchema` class. So I am not sure if this would be worth it, I would just like to start a discussion.

**Comment by anton-k** [comment]
We need it to create swagger and OpenApi schema
