### ISSUE TITLE
HelloWorld examples don't compile?

### ISSUE THREAD

**Issue by glensargent** [anton-k/mig#71]
I'm new to haskell so perhaps I could be missing something painfully obvious, but I've just installed w/ cabal and tried to compile the hello world example:

```
import Mig.Json.IO

-- | Starts server on port 8085.
main :: IO ()
main = runServer 8085 server

-- | The server definition
server :: Server IO
server = "api/v1/hello" /. hello

-- | The handler definition as a function
hello :: Get (Resp Text)
hello = pure $ ok "Hello World"
```

I get the following errors:

```
app/Main.hs:9:10: error: [GHC-83865]
    • Couldn't match type ‘[Char]’ with ‘Path’
      Expected: Path
        Actual: String
    • In the first argument of ‘(/.)’, namely ‘"api/v1/hello"’
      In the expression: "api/v1/hello" /. hello
      In an equation for ‘server’: server = "api/v1/hello" /. hello
  |
9 | server = "api/v1/hello" /. hello
  |          ^^^^^^^^^^^^^^

app/Main.hs:13:19: error: [GHC-83865]
    • Couldn't match type ‘[Char]’ with ‘Text’
      Expected: RespBody (Resp Text)
        Actual: String
    • In the first argument of ‘ok’, namely ‘"Hello World"’
      In the second argument of ‘($)’, namely ‘ok "Hello World"’
      In the expression: pure $ ok "Hello World"
   |
13 | hello = pure $ ok "Hello World"
   |                   ^^^^^^^
```

The second I can easily resolve w/ Data.Text & Pack, but I can't find any path functions in the mig lib to satisfy the mismatched type in the first err. I'm not experienced enough with haskell and the differences between stack and cabal projects so sorry in advance if this is something ridiculous. 

Are the example projects out dated, or is the documentation missing something on setup? I was reading these docs also: https://anton-k.github.io/mig/

Also worth adding that the hello world example in the repo is different to the documentation

**Comment by glensargent** [comment]
from what I understand, stack uses default packages from stackage as default, so could be that i'm missing common libs

**Comment by anton-k** [comment]
It uses a language extension `OverloadedStrings`. This extension let us use string literals on types which are convertible from string.
Normally I add it on package level, then there is no need to write it in the code, see example for
* [stack](https://github.com/anton-k/mig/blob/main/mig/package.yaml#L35)
* or for [cabal](https://github.com/anton-k/mig/blob/main/mig/mig.cabal#L63)

Also this extension can be activated per module if you write as a top line of your `Main.hs` file:

```haskell
{-# Language OverloadedStrings #-}
```

**Comment by anton-k** [comment]
The simplest route to try out the library if you are completely new is to try out the code from examples.
* Install stack
* clone mig's repo
* `cd` Navigate to [examples](https://github.com/anton-k/mig/tree/main/examples/mig-example-apps)
* do: `stack install` to install poper compiler
* try out various commands from the [`Makefile`](https://github.com/anton-k/mig/blob/main/examples/mig-example-apps/Makefile)

**Comment by glensargent** [comment]
Aaah I see, I missed that, it seems like a lot of people tend to declare it at the top of the file so this is the first time i've seen it done this way. I appreciate your fast response, works fine now, thanks!
